apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: frpserverreferences.experimental.milkshakes.cloud
spec:
  group: experimental.milkshakes.cloud
  names:
    kind: FrpServerReference
    listKind: FrpServerReferenceList
    plural: frpserverreferences
    singular: frpserverreference
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: FrpServerReference is the Schema for the frpserverreferences API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: FrpServerReferenceSpec defines the desired state of FrpServerReference
            properties:
              frp_server_addr:
                description: Addr that the FRP server is listening for frp client connections on
                type: string
              frp_server_port:
                description: Port that the FRP server will listen for frp client connections on
                maximum: 65535
                minimum: 1
                type: integer
              frp_endpoint_addr:
                description: Addr that the FRP server is listening for proxied connections on
                type: string
              frp_endpoint_dns:
                description: DNS name that the FRP server is listening for proxied connections on, if available
                type: string
            required:
            - frp_server_addr
            - frp_server_port
            - frp_endpoint_addr
            type: object
          status:
            description: FrpServerReferenceStatus defines the observed state of FrpServerReference
            properties:
              healthy:
                description: Shows "healthy" or a related error as the result of health
                  checks (soon tm)
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
